---
title: "Average data before/after COVID"
output: html_document
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(dplyr)
library(plotly)
library(ggpubr)

theme_set(theme_minimal())

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

```{r load data, include=FALSE}
import_value_df = 
  read_csv("data/cleaned data/import_value_combined.csv") %>% 
  mutate(
    product_type = recode(product_type, "Vegetables & preparations" = "Vegetables and preparations","Fruits & preparations" = "Fruits and preparations", "Grains & feeds" = "Grains and feeds","Beef & veal" = "Beef and veal", "Coffee & products" = "Coffee and products", "Cotton & linters" = "Cotton and linters","Cut flowers & nursery stock" = "Cut flowers and nursery stock","Oilseeds & products" = "Oilseeds and products","Red meats & products" = "Red meats and products", "Sugar & related products" = "Sugar and related products","Tree nuts & preparations" = "Tree nuts and preparations")
  )

export_value_df = 
  read_csv("data/cleaned data/export_value_combined.csv") %>% 
  mutate(
    product_type = recode(product_type,"Cotton & linters" = "Cotton and linters","Red meats & products" = "Red meats and products","Tree nuts & preparations" = "Tree nuts and preparations","Grains & feeds" = "Grains and feeds", "Hides & skins" = "Hides and skins","Poultry meats & products" = "Poultry meats and products","Fruits & products" = "Fruits and products","Sugar & tropical products" = "Sugar and tropical products","Animal feeds & oil meal" = "Animal feeds and oil meal")
  )

import_volume_df = 
  read_csv("data/cleaned data/import_volume_combined.csv") %>% 
  mutate(
    product_type = recode(product_type, "Vegetables & preparations" ="Vegetables and preparations","Fruits & preparations" = "Fruits and preparations", "Grains & feeds" = "Grains and feeds","Beef & veal" = "Beef and veal", "Coffee & products" = "Coffee and products", "Cotton & linters" = "Cotton and linters","Cut flowers & nursery stock" = "Cut flowers and nursery stock","Oilseeds & products" = "Oilseeds and products","Red meats & products" = "Red meats and products", "Sugar & related products" = "Sugar and related products","Tree nuts & preparations" = "Tree nuts and preparations")
  )

export_volume_df = 
  read_csv("data/cleaned data/export_volume_combined.csv") %>% 
  mutate(
    product_type = recode(product_type,"Cotton & linters" = "Cotton and linters","Red meats & products" = "Red meats and products","Tree nuts & preparations" = "Tree nuts and preparations","Grains & feeds" = "Grains and feeds", "Hides & skins" = "Hides and skins","Poultry meats & products" = "Poultry meats and products","Fruits & products" = "Fruits and products","Sugar & tropical products" = "Sugar and tropical products","Animal feeds & oil meal" = "Animal feeds and oil meal")
  )
```


```{r message=FALSE}
before_covid_import_value =
  import_value_df %>% 
  filter(year == "2018" | year == "2019") %>% 
  add_column("Covid_19" = "before") %>% 
  group_by(product_type, Covid_19) %>% 
  summarize(average = mean(import_value)) 
  

after_covid_import_value =
  import_value_df %>% 
  filter(year == "2020" | year == "2021") %>% 
  add_column("Covid_19" = "after") %>% 
  group_by(product_type, Covid_19) %>% 
  summarize(average = mean(import_value)) 

covid_import_value_df = 
  rbind(before_covid_import_value,after_covid_import_value)

before_covid_export_value =
  export_value_df %>% 
  filter(year == "2018" | year == "2019") %>% 
  add_column("Covid_19" = "before") %>% 
  group_by(product_type, Covid_19) %>% 
  summarize(average = mean(export_value))

after_covid_export_value =
  export_value_df %>% 
  filter(year == "2020" | year == "2021") %>% 
  add_column("Covid_19" = "after") %>% 
  group_by(product_type, Covid_19) %>% 
  summarize(average = mean(export_value)) 

covid_export_value_df = 
  rbind(before_covid_export_value,after_covid_export_value)

```


### Average Import Value Before/After Covid From 2018 To 2021


```{r}
covid_import_value_plot =  
  covid_import_value_df %>%
  ggplot(aes(x = product_type, y = average, fill = Covid_19)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    x = "Product Type",
    y = "Average Import Values"
  ) +
  theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 6)
    ) 

```

<center>
```{r}
ggplotly(covid_import_value_plot)
```
</center>


### Average Export Value Before/After Covid From 2018 To 2021

```{r}
covid_export_value_plot =  
  covid_export_value_df %>%
  ggplot(aes(x = product_type, y = average, fill = Covid_19)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    x = "Product Type",
    y = "Average Export Values"
  ) +
  theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 6)
    )


```

<center>
```{r}
ggplotly(covid_export_value_plot)
```
</center>


```{r message=FALSE}
before_covid_import_volume =
  import_volume_df %>%
  filter(year == "2018" | year == "2019") %>% 
  add_column("Covid_19" = "before") %>% 
  group_by(product_type, Covid_19) %>% 
  summarize(average = mean(import_volume))

after_covid_import_volume =
  import_volume_df %>% 
  filter(year == "2020" | year == "2021") %>% 
  add_column("Covid_19" = "after") %>% 
  group_by(product_type, Covid_19) %>% 
  summarize(average = mean(import_volume))

covid_import_volume_df = 
  rbind(before_covid_import_volume,after_covid_import_volume)

before_covid_export_volume =
  export_volume_df %>%
  filter(year == "2018" | year == "2019") %>% 
  add_column("Covid_19" = "before") %>% 
  group_by(product_type, Covid_19) %>% 
  summarize(average = mean(export_volume)) 

after_covid_export_volume =
  export_volume_df %>% 
  filter(year == "2020" | year == "2021") %>% 
  add_column("Covid_19" = "after") %>% 
  group_by(product_type, Covid_19) %>% 
  summarize(average = mean(export_volume)) 

covid_export_volume_df = 
  rbind(before_covid_export_volume,after_covid_export_volume)
```

## Average Import Volume Before/After Covid From 2018 To 2021

```{r}
covid_import_volume_plot =  
  covid_import_volume_df %>%
  ggplot(aes(x = product_type, y = average, fill = Covid_19)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    x = "Product Type",
    y = "Average Import Volumes"
  ) +
  theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 6)
    ) 


```

<center>
```{r}
ggplotly(covid_import_volume_plot)
```
</center>

## Average Export Volume Before/After Covid From 2018 To 2021

```{r}
covid_export_volume_plot =  
  covid_export_volume_df %>%
  ggplot(aes(x = product_type, y = average, fill = Covid_19)) +
  geom_bar(stat = "identity", position = "dodge") +
  labs(
    x = "Product Type",
    y = "Average Export Volumes"
  ) +
  theme(
    axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1, size = 6)
    )

```

<center>
```{r}
ggplotly(covid_export_volume_plot)
```
</center>
