---
title: "Covid Cases vs. Export and Import Volume"
output: html_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)

library(plotly)

knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 6,
  fig.height = 4,
  out.width = "90%"
)



theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


```{r, message=FALSE, echo = FALSE}
## Import data 
covid = 
  read_csv("./data/covid_data_monthly.csv") %>% 
  mutate(month = month.name[as.numeric(month)],
         month = as.factor(month),
         month = ordered(month, levels = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")),
         year = as.character(year),
         Confirmed_of_Month = as.numeric(Confirmed_of_Month))

## take a look at covid plot 
covid %>% 
  ggplot(aes(x = month, y = Confirmed_of_Month, color = year)) + 
  geom_line(aes(group = year)) +
  geom_point(size = 1.5) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) + 
  labs(
    title = "Monthy Covid Cases",
    x = "Month",
    y = "Confirmed cases per month",
    color = "Year"
  )

export_volume_df = 
  read_csv("./data/cleaned data/export_volume_combined.csv") %>% 
  mutate(month = as.factor(month),
         month = recode(month, "Feburary" = "February"),
         month = ordered(month, levels = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")),
         year = as.character(year))

export_volume_df %>% 
  group_by(month,year) %>% 
  summarize(sum_of_export = sum(export_volume)) %>% 
  ggplot(aes(x = month, y = sum_of_export, color = year)) + 
  geom_line(aes(group = year)) +
  geom_point(size = 1.5) +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) + 
  labs(
    title = "Monthy Export",
    x = "Month",
    y = "Total export volume (metric tons)",
    color = "Year"
  )
  

import_volume_df = 
  read_csv("./data/cleaned data/import_volume_combined.csv") %>% 
  mutate(month = as.factor(month),
         month = recode(month, "Feburary" = "February"),
         month = ordered(month, levels = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")),
         year = as.character(year))

import_volume_df %>% 
  group_by(month,year) %>% 
  summarize(sum_of_import = sum(import_volume)) %>% 
  ggplot(aes(x = month, y = sum_of_import, color = year)) + 
  geom_line(aes(group = year)) +
  geom_point(size = 1.5) + 
   theme(axis.text.x = element_text(angle = 45, vjust = 1, hjust = 1)) + 
  labs(
    title = "Monthy Import",
    x = "Month",
    y = "Total import volume (metric tons)",
    color = "Year"
  )

combined_df = list(covid, export_volume_df, import_volume_df) %>% 
  reduce(left_join, by = c("year", "month"), all = TRUE) %>%
  janitor::clean_names() %>% 
  rename("export_product_type" = "product_type_x",
         "import_product_type" = "product_type_y") 

```

```{r interactive_data_table}
combined_df %>%
  rename(Month = month,
         Year = year,
         "Monthly Confirmed Cases" = confirmed_of_month,
         "Number of Deaths" = deaths_of_month,
         "Number of Recovered" = recovered_of_month,
         "Number of Active Cases" = active_of_month, 
         "Export Product Type" = export_product_type,
         "Export Volume" = export_volume, 
         "Import Product Type" = import_product_type, 
         "Import Volume" = import_volume) %>% 
DT::datatable(., class = 'compact',
              rownames = FALSE,
              caption = 'Table')
```

## Export Volume vs. Covid Cases

```{r, message=FALSE, echo =FALSE}
export_fit = lm(export_volume ~ confirmed_of_month, data = combined_df)
summary(export_fit)

export_df = 
  combined_df %>% 
  na.omit() %>% 
  nest(data = confirmed_of_month:export_volume) %>% 
  mutate(
    lm_fits = map(.x = data, ~ lm(export_volume ~ confirmed_of_month + deaths_of_month, data = .x)),
    lm_results = map(lm_fits, broom::tidy)) %>% 
  select(month, year, lm_results) %>% 
  unnest(lm_results) 
  
export_df %>% 
  na.omit() %>% 
  ggplot(aes(x = estimate)) +
  geom_density() +
  labs(
    x = "Estimate",
    y = "Density"
  )

export_plot = combined_df %>% 
  group_by(month, year, confirmed_of_month) %>% 
  summarize(export_sum = sum(export_volume)) %>% 
ggplot(aes(x = confirmed_of_month, y = export_sum)) +
  geom_point(alpha = 0.5) +
  scale_y_continuous() +
  geom_smooth(se = F, color = "red", method = "lm", size = 1, linetype = 2) +
  labs(title = "Covid Cases vs. Export Volume", 
       x = "Covid Cases", 
       y = "Export Volume (metric tons)")

combined_df %>% 
  mutate(
    text_label = str_c("Confirmed Cases: $", confirmed_of_month, "\nExport Volume: ", export_volume)) %>% 
  plot_ly(
    x = ~ confirmed_of_month, y = ~ export_volume, type = "box", mode = "markers", color = ~month, text = ~text_label, alpha = 0.5)%>%
  layout(xaxis = list(title = "Confrimed cases per month"),
         yaxis = list(title = "Export volume (metirc tons)"))


```


## Import Volume vs. Covid Cases 

```{r, message=FALSE, echo =FALSE}
import_fit = lm(import_volume ~ confirmed_of_month, data = combined_df)
summary(import_fit)

import_df = 
  combined_df %>% 
  na.omit() %>% 
  nest(data = confirmed_of_month:import_volume) %>% 
  mutate(
    lm_fits = map(.x = data, ~ lm(import_volume ~ confirmed_of_month, data = .x), na.action = na.omit()),
    lm_results = map(lm_fits, broom::tidy)) %>% 
  select(month, year, lm_results) %>% 
  unnest(lm_results) 
  
import_df %>% 
  ggplot(aes(x = estimate)) +
  geom_density() +
  labs(
    x = "Estimate",
    y = "Density"
  )


import_plot = combined_df %>% 
  group_by(month, year, confirmed_of_month) %>% 
  summarize(import_sum = sum(import_volume)) %>% 
  ggplot(aes(x = confirmed_of_month, y = import_sum)) +
  geom_point(alpha = 0.5) +
  scale_y_continuous() +
  geom_smooth(se = F, color = "red", method = "lm", size = 1, linetype = 2) +
  labs(title = "Covid Cases vs. Import Volume", 
       x = "Covid Cases", 
       y = "Import Volume (metric tons)")
  

combined_df %>% 
  group_by(month, year, confirmed_of_month) %>% 
  summarize(import_sum = sum(import_volume)) %>% 
  mutate(
    text_label = str_c("Confirmed Cases: $", confirmed_of_month, "\nImport Volume: ", import_sum)) %>% 
  plot_ly(
    x = ~ confirmed_of_month, y = ~ import_sum, type = "scatter", mode = "markers", color = ~month, text = ~text_label)%>%
  layout(xaxis = list(title = "Covid cases per month"), 
       yaxis = list(title = "Sum of import volume per month (metric tons)"))
```

```{r, message=FALSE, echo = FALSE}
ggpubr::ggarrange(import_plot, export_plot)
```
