---
title: "Covid Cases vs. Export/Import Volume"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: scroll
---

```{r setup, include=FALSE}
library(tidyverse)
library(dplyr)
library(plotly)

knitr::opts_chunk$set(
  echo = TRUE,
  warning = FALSE,
  fig.width = 8,
  fig.height = 6,
  out.width = "90%"
)


theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


```{r include=FALSE}
## Import data 
covid = 
  read_csv("./data/covid_data_monthly.csv") %>% 
  mutate(month = month.name[as.numeric(month)],
         month = as.factor(month),
         month = ordered(month, levels = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")),
         year = as.character(year),
         Confirmed_of_Month = as.numeric(Confirmed_of_Month))

export_volume_df = 
  read_csv("./data/cleaned data/export_volume_combined.csv") %>% 
  mutate(month = as.factor(month),
         month = recode(month, "Feburary" = "February"),
         month = ordered(month, levels = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")),
         year = as.character(year))

import_volume_df = 
  read_csv("./data/cleaned data/import_volume_combined.csv") %>% 
  mutate(month = as.factor(month),
         month = recode(month, "Feburary" = "February"),
         month = ordered(month, levels = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")),
         year = as.character(year))

combined_df = list(covid, export_volume_df, import_volume_df) %>% 
  reduce(left_join, by = c("year", "month"), all = TRUE) %>%
  janitor::clean_names() %>% 
  rename("export_product_type" = "product_type_x",
         "import_product_type" = "product_type_y") 
```

# Data Sums

## Column 1

### confirmation of month
```{r echo=FALSE}
## take a look at covid plot 
com =
covid %>% 
  ggplot(aes(x = month, y = Confirmed_of_Month, color = year)) + 
  geom_line(aes(group = year)) +
  geom_point(size = 1.5) +
  xlab("Month") +
  ylab("Confirmed cases per month")

ggplotly(com)
```
## Column 2

### sum of export
```{r echo=FALSE}
soe =
export_volume_df %>% 
  group_by(month,year) %>% 
  summarize(sum_of_export = sum(export_volume)) %>% 
  ggplot(aes(x = month, y = sum_of_export, color = year)) + 
  geom_line(aes(group = year)) +
  geom_point(size = 1.5) +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))+
  xlab("Month") +
  ylab("Sum of export volume (metric tons)")

ggplotly(soe)
```

## Column 3

### sum of import
```{r echo=FALSE}
soi =
import_volume_df %>% 
  group_by(month,year) %>% 
  summarize(sum_of_import = sum(import_volume)) %>% 
  ggplot(aes(x = month, y = sum_of_import, color = year)) + 
  geom_line(aes(group = year)) +
  geom_point(size = 1.5) + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1)) +
  xlab("Month") +
  ylab("Sum of import volume (metric tons)")

ggplotly(soi)
```


# Regressions

## Column 1

### model
```{r echo=FALSE}
export_fit = lm(export_volume ~ confirmed_of_month, data = combined_df)
summary(export_fit)
```

### export volume estimates density
```{r echo=FALSE}
export_df = 
  combined_df %>% 
  na.omit() %>% 
  nest(data = confirmed_of_month:export_volume) %>% 
  mutate(
    lm_fits = map(.x = data, ~ lm(export_volume ~ confirmed_of_month + deaths_of_month, data = .x)),
    lm_results = map(lm_fits, broom::tidy)) %>% 
  select(month, year, lm_results) %>% 
  unnest(lm_results) 

deoc =   
export_df %>% 
  na.omit() %>% 
  ggplot(aes(x = estimate)) +
  geom_density()

ggplotly(deoc)
```
### export volume over cases

```{r echo=FALSE}
export_plot = combined_df %>% 
  group_by(month, year, confirmed_of_month) %>% 
  summarize(export_sum = sum(export_volume)) %>% 
ggplot(aes(x = confirmed_of_month, y = export_sum)) +
  geom_point() +
  scale_y_continuous() +
  geom_smooth(se = F, color = "red", method = "lm", size = 1, linetype = 2) +
  labs(title = "Covid Cases vs. Export Volume", 
       x = "Covid cases", 
       y = "Export volume (metric tons")

combined_df %>% 
  mutate(
    text_label = str_c("Confirmed Cases: $", confirmed_of_month, "\nExport Volume: ", export_volume)) %>% 
  plot_ly(
    x = ~ confirmed_of_month, y = ~ export_volume, type = "scatter", mode = "markers", color = ~month, text = ~text_label, alpha = 0.5)%>%
  layout(xaxis = list(title = "Covid cases per month"), 
       yaxis = list(title = "Sum of import volume per month (metric tons)"))


```

## Column 2

### model

```{r echo=FALSE}
import_fit = lm(import_volume ~ confirmed_of_month, data = combined_df)
summary(import_fit)
```
### import volume estimates density
```{r echo=FALSE}
import_df = 
  combined_df %>% 
  na.omit() %>% 
  nest(data = confirmed_of_month:import_volume) %>% 
  mutate(
    lm_fits = map(.x = data, ~ lm(import_volume ~ confirmed_of_month, data = .x), na.action = na.omit()),
    lm_results = map(lm_fits, broom::tidy)) %>% 
  select(month, year, lm_results) %>% 
  unnest(lm_results) 

dioc =  
import_df %>% 
  ggplot(aes(x = estimate)) +
  geom_density()

ggplotly(dioc)
```

### import volume over cases 



```{r echo=FALSE}
import_plot = combined_df %>% 
  group_by(month, year, confirmed_of_month) %>% 
  summarize(import_sum = sum(import_volume)) %>% 
  ggplot(aes(x = confirmed_of_month, y = import_sum)) +
  geom_point(alpha = 0.5) +
  scale_y_continuous() +
  geom_smooth(se = F, color = "red", method = "lm", size = 1, linetype = 2) +
  labs(title = "Covid Cases vs. Import Volume", 
       x = "Covid Cases", 
       y = "Import Volume")
  

combined_df %>% 
  group_by(month, year, confirmed_of_month) %>% 
  summarize(import_sum = sum(import_volume)) %>% 
  mutate(
    text_label = str_c("Confirmed Cases: $", confirmed_of_month, "\nImport Volume: ", import_sum)) %>% 
  plot_ly(
    x = ~ confirmed_of_month, y = ~ import_sum, type = "scatter", mode = "markers", color = ~month, text = ~text_label, alpha = 0.5)
```

## comparison of import and export

### import

```{r echo=FALSE}
import_plot
```

### export
```{r echo=FALSE}
export_plot
```
