---
title: "Project Report"
subtitle: "Correlation between US Foreign Agricultural Trade and COVID-19 Impact"
output: 
  html_document:
    toc: true
    toc_float: true
---
## Project Motivation
The message Americans have been getting about inflation in recent months can be expressed in one word: frightening. Last year, as COVID-19 affected the world economy and disrupted trade flows, which also has had unprecedented effects on all dimensions of human life. Yet, it is certainly not our imagination: groceries do cost more now than prior to pandemic. The increase in food prices that we’ve seen over the past eight months is real and meaningful. According to the U.S. Bureau of Labor Statistics, food prices overall rose about 4.6% since September 2020. 

The effects of pandemic have been felt in almost every sector, and the agricultural market is no different. Our project intends to look deeper into the impact of Covid-19 on agricultural trade and how it's affecting both supply and demand.

<br>

## Initial Questions
Initially, we wanted to see if the emergence of Covid-19 pandemic has any effect on U.S. agricultural imports and exports(using the U.S. Agricultural Trade Data and Public COVID-19 daily report). In addition, to identify the top agricultural products that have been impacted by Covid-19 in foreign trade, and also whether Covid cases were interrelated with export and import volumes. We are also interested in looking at specifically if Covid-19 virus brings any changes to trade between China and U.S by looking at monthly data. As international trade being a victim of the current Covid-19 pandemic, we hoped that by exploring agricultural trade and Covid cases, we could see if agricultural sectors particularly were heavily affected. 

<br>

## Data
### Data Sources
In this project, we used the Foreign Agricultural Trade of the United States (FATUS) data of 2018 to 2021 from the USDA public government research service 
[Agricaltural Trade Data Reference](https://www.ers.usda.gov/data-products/foreign-agricultural-trade-of-the-united-states-fatus/u-s-agricultural-trade-data-update/). The data contains information on U.S. agricultural trade, values and volumes of high-value and bulk commodities, and top country export destinations and import sources for total U.S. agricultural trade. 
<br>

Also, the Public COVID-19 daily report from COVID-19 Data Repository by the Center for Systems Science and Engineering (CSSE) at Johns Hopkins University:
[Covid-19 Data Reference](https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports_us).

<br>

### Data Cleaning

**Agricultural Trade Data:** There were 4 Excel files each year from January 2018 to September 2021 : U.S. agricultural exports, U.S. agricultural imports, Top 10 U.S. agricultural export markets for wheat, corn, soybeans, and cotton by volume, and Top 10 sources of U.S. agricultural imports of fruits and vegetables by value. For each individual Excel files, we extracted and combined monthly data from each individual sheet in the file for both export/import values and volumes, and variable names were cleaned and renamed. Then we performed `pivot_longer()` to format the data in displaying export/import values and volumes for each product types filtered by year and month. Similarly, for the Top 10 agricultural import and export datasets, we extracted and combined monthly data for each commodity. We used `pivot_longer()` to format the data in displaying export/import values for each commodities and (import/export) countries, and filtered by year and month. Then, `rbind()` was used to combined all the different commodities for each year into one dataframe. Lastly, we combined all the years into one data for each file, resulting in total of 4 datasheets: Export (2018-2021), Import (2018-2021), Top 10 export (2018-2021), and Top 10 import (2018-2021) which will then be imported into R for later analysis. 

**Covid-19 Data:** This data repository operated by Johns Hopkins University Center for Systems Science and Engineering (JHU CSSE) was imported into R and combined the daily report for covid cases in U.S. into one dataframe. Data and variable names were cleaned, missing values were removed, date variable was mutated and separated into two columns (Month and Year), and kept information on confirmed cases, active cases number of deaths, and number of recovered. Then, we sum up the cases by month using the sum function. Visualizations and graphs rely on count of cases was ploted as needed.

<br>

## Exploratory Analysis
### Section 1. Average monthly import value/volume before (2018-2019) and after (2020-2021) Covid-19
We defined year 2018-2019 as period before Covid-19, year 2020-2021 as period after Covid-19, and calculated the average monthly import/export values/volumes before and after Covid-19 with the same month of year combined. We also calculated average monthly import/export values/volumes for each year as reference. [View Plots](Spaghetti-before-after-COVID---DB.html)

### Section 2. Average export/import value/volume of each product type before (2018-2019) and after (2020-2021) Covid-19
We calculated the average export/import value/volume of each product type for 2018-2019 and 2020-2021, and created side-by-side bar chart colored by before/after Covid-19. [View Plots](Bar-before-after-COVID-DB.html)

### Section 3. Import/Export change with China under the pandemic
We used the data of top 10 U.S. export markets for soybeans, corn, wheat, and cotton (by volume) in each year from 2018 to 2021. Due to the complexity of original data, we only analyzed the volume of export to China, which is a crucial and one of the largest oversea market of US. We calculated the total export volume of China for 2018-2019 and 2020-2021 and made a two-panel bar plot with country as x-axis, export volume as y-axis, and colored by commodity. Since the data for top 10 import sources only has import value, we did the same analysis and visualization on import dataset and generated another plot with y-axis of import value. The original dataset only contains data of countries with top 10 highest volume of export / value of import. If China is not in the top 10 list for certain commodity during certain month, then the data will not be shown in the plot. [View Plots](China_import---DB.html)

### Section 4. Correlation between the number of Covid-19 cases in the U.S. and the volume of import/exports
We plotted the correlation between the number of Covid-19 cases in the U.S. and the volume of import/exports with a regression line generated by linear regression, with the number of Covid-19 cases by month as x-axis and monthly volume of monthly imports/exports as y-axis. [View Plots](Cases-vs-volume---DB.html)

<br>

## Key Findings

* Covid cases gradually increase in both 2020 and 2021.

* The Covid-19 cases of 2020 follow an exponential pattern.

* The trend for 2021 Covid-19 cases seem to follow a square root function.

* Total export steeply increases from July to December in 2020, while decreased significantly from January through September in 2021.

* Import and export data shows a rough seasonal pattern: imports of each year peak at spring, exports peak at spring and late autumn.

* No apparent association between covid cases and export or import. Covid Cases vs. Import Volume shows a slight positive relationship, while Covid Cases vs. Export Volume shows a relative negative association.

* import and export both slightly increased after Covid-19 pandemic.

* export volume of sorghum is especially prominent

*  Volumes of imports from China do not change much after Covid-19. Volumes of export of corn, soybean, and wheat to China all ascended. Only the volume of cotton export decreased after Covid-19.

* It is difficult to make an acceptable model of U.S. agricultural imports and exports using only the number of COVID-19 cases as an indicator.


<br>

## Discussions

For the Covid-19 monthly confirmed cases, we found it increases since April 2020 till present, but the increasing rate has fallen in 2021, which is conform to US COVID Vaccination timeline ([reference](https://ourworldindata.org/covid-vaccinations?country=USA) ).

The seasonal pattern of agricultural import and export might be due to the characteristics that agricultural products yield are naturally more seasonal. In the spring and summer season, which are not primarily the harvest season, countries and regions had consumed plenty of their own produced goods, therefore, the market activity seems to be more active.(There were peaks observed for both import and export.)

As for the difference analysis of each product category, we found that the majority of products were not significantly affected by the epidemic (import and export increase naturally every year, so the increase might not be attributed to the epidemic).  For example in China, America's largest market for agricultural imports and exports, we did not find a significant effect of Covid-19 on values of import from China. One possible explanation for this is that China responded quickly in controlling the Covid-19 pandemic within a few months in the beginning of 2020, so fruit and vegetable markets in China were mostly stable and were hardly influenced by Covid-19. However, the volume of export to China did change remarkably for some particular categories. The export volume of corn to China increased after Covid-19, while the export volume of cotton decreased. The former maybe because corn is an important ingredient for alcohol (demand has soared in quarantine campaigns) and the latter maybe because of the Xinjiang cotton incident. Due to the boycott of Xinjiang cotton by other countries, the Chinese market tended to consume more of its own cotton, and the demand for imports fell.  

For the data of import and export to China in general, volumes of export of corn, soybean, and wheat to China all ascended after Covid-19. One possible explanation for this is that the exchange rate of the U.S. dollar has been continuously decreasing after Covid-19, so commodities from U.S. were in cheaper prices for China to import comparing with previous years, which consequently resulting in an increase in import volume from the U.S. (i.e. the export volume from the U.S. to China). 

Finally, our attempt to use Covid-19 cases to predict and import/export data failed to have any meaningful quality measures. Large number of outliers showing the Covid-19 cases itself as an indicator is not enough for plausible modeling. Further research may be needed in order to provide more accurate predictions of the model. We also need to consider other potential variables such as the economic changes of other countries, climate change, government policies or restrictions, etc. that could affect US import/export. 


<br>

## Conclusion

Our data analysis found some development regularity of data and the characteristics of agricultural import and export in the US, but could not reflect the specific relationship between these two statistics. So far, all of our interpretations of data analysis results are conjecture.


<br>

## Contributors
* AnMei Chen 
* Lynn Chen
* Xuanhe Chen
* Zoey Zhao
* Xinyi Zhou

