---
title: "Average monthly data before/after COVID"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(dplyr)
library(plotly)
library(readxl)
library(patchwork)

theme_set(theme_minimal())

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```

<!--
Column {data-width=650}
-----------------------------------------------------------------------
-->
```{r}
export_value = read_excel("./data/export_value_combined.xlsx") %>%
  mutate(type = "export") %>%
  rename(value = export_value)
import_value = read_excel("./data/import_value_combined.xlsx") %>%
  mutate(type = "import") %>%
  rename(value = import_value)

value = rbind(export_value, import_value) %>%
  mutate(year = as.character(year),
         month = recode(month, "Feburary" = "February"),
         month = as.factor(ordered(month, levels = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")))) %>%
  group_by(year, month, type) %>%
  mutate(monthly_total = sum(value),
         covid_19 = ifelse(year %in% c("2018", "2019"), "before", "after")) %>% 
  group_by(covid_19, month, type) %>%
  mutate(avg_value = mean(monthly_total)) 

va_BACVD =
value %>%
  ggplot(aes(x = month, y = avg_value, color = covid_19, group = covid_19)) +
  geom_line() +
  labs(y = "average value", title = "spaghetti plot of average monthly export/import values before/after Covid-19") +
  theme(axis.text.x = element_text(angle = 70, vjust = 0.5, hjust = 0.5)) +
  facet_grid(. ~ type)

va_ECHY =
value %>%
  ggplot(aes(x = month, y = monthly_total, color = year, group = year)) +
  geom_line() +
  labs(y = "average value", title = "spaghetti plot of the average monthly export/import values for each year") +
  theme(axis.text.x = element_text(angle = 70, vjust = 0.5, hjust = 0.5)) +
  facet_grid(. ~ type)

ggplotly(va_BACVD)
ggplotly(va_ECHY)
```

## spaghetti plot of the average monthly export or import volumes before and after Covid-19

```{r}
export_volume = 
  read_excel("./data/export_volume_combined.xlsx") %>%
  mutate(type = "export") %>%
  rename(volume = export_volume)
import_volume = 
  read_excel("./data/import_volume_combined.xlsx") %>%
  mutate(type = "import") %>%
  rename(volume = import_volume)

volume = rbind(export_volume, import_volume) %>%
  mutate(year = as.character(year),
         month = recode(month, "Feburary" = "February"),
         month = as.factor(ordered(month, levels = c("January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December")))) %>%
  group_by(year, month, type) %>%
  mutate(monthly_total = sum(volume),
         covid_19 = ifelse(year %in% c("2018", "2019"), "before", "after")) %>% 
  group_by(covid_19, month, type) %>%
  mutate(avg_volume = mean(monthly_total)) 

im_volume_plot = volume %>%
  filter(type == "import") %>%
  ggplot(aes(x = month, y = avg_volume, color = covid_19, group = covid_19)) +
  geom_line() +
  labs(y = "", title = "import") +
  theme(axis.text.x = element_text(angle = 70, vjust = 0.5, hjust = 0.5))

ex_volume_plot = volume %>%
  filter(type == "export") %>%
  ggplot(aes(x = month, y = avg_volume, color = covid_19, group = covid_19)) +
  geom_line() +
  labs(y = "average volume", title = "export") +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle = 70, vjust = 0.5, hjust = 0.5))

#vo_BACVD = 
#  ex_volume_plot + im_volume_plot 

ggplotly(ex_volume_plot)
ggplotly(im_volume_plot)
```


## spaghetti plot of the average monthly export or import volumes for each year

```{r}
im_volume_plot_byyear = volume %>%
  filter(type == "import") %>%
  ggplot(aes(x = month, y = monthly_total, color = year, group = year)) +
  geom_line() +
  labs(y = "", title = "import") +
  theme(axis.text.x = element_text(angle = 70, vjust = 0.5, hjust = 0.5))

ex_volume_plot_byyear = volume %>%
  filter(type == "export") %>%
  ggplot(aes(x = month, y = monthly_total, color = year, group = year)) +
  geom_line() +
  labs(y = "average volume", title = "export") +
  theme(legend.position = "none") +
  theme(axis.text.x = element_text(angle = 70, vjust = 0.5, hjust = 0.5))

ggplotly(ex_volume_plot_byyear)
ggplotly(im_volume_plot_byyear)
```


